### ISSUE TITLE
Benefits of Compressing Unsorted uint64_t

### ISSUE THREAD

**Issue by rapoth** [cruppstahl/libvbyte#3]
I was playing around with libvbyte. First of all, thank you for the library. It works great on sorted numbers. 

Using test.cc as a starting point, I was trying to compress unsorted numbers (dataset attached) but the size of the result set increases compared to the original dataset. 

- Original dataset (txt): 13.5 MB
- Original dataset (binary): 5.4 MB
- Encoded dataset (binary): 6.7 MB

I can understand that this could be due to the unsorted nature of the dataset but I am curious what benefits I would get by using libvbyte on unsorted datasets (where the result set size could potentially increase). Or do you recommend that I always sort datasets before using your library?

Thank you!

[data.txt](https://github.com/cruppstahl/libvbyte/files/812717/data.txt)

**Comment by cruppstahl** [comment]
In some cases, the varbyte encoding can require more storage than the unencoded binary number, and this seems to be the case with your data because your numbers are so big. Big numbers require many bytes, and each byte "wastes" one bit for the "continuation bit". Here is an explanation of the algorithm: http://nlp.stanford.edu/IR-book/html/htmledition/variable-byte-codes-1.html

When you sort your numbers then libvbyte only compresses the deltas. These deltas are typically very small and therefore require much less storage.
